//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorSetApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptProduct
    {
        public int ReceiptId { get; set; }
        public int ProductId { get; set; }
        public int Count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
